@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts HTTP/1.1
content-type: application/json

{
    "name": "isaac",
    "email": "isaac@gmail.com",
    "password": "65432145"
}

###

# @name authenticate
POST {{baseUrl}}/sessions HTTP/1.1
content-type: application/json

{
    "email": "bruno@gmail.com",
    "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions HTTP/1.1
content-type: application/json

# {
#     "email": "bruno@gmail.com",
#     "password": "123456"
# }