@baseUrl = http://localhost:3333

@authToken = {{authenticate.response.body.access_token}}


# @name create_account
POST {{baseUrl}}/accounts HTTP/1.1
content-type: application/json

{
    "name": "isaac",
    "email": "isaac@gmail.com",
    "password": "65432145"
}

###

# @name authenticate
POST {{baseUrl}}/sessions HTTP/1.1
content-type: application/json

{
    "email": "isaac@gmail.com",
    "password": "654321"
}

###

# @name create_question
POST {{baseUrl}}/questions HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Node",
    "content": "Node por de baixo dos panos"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

###

# @name logout
POST {{baseUrl}}/auth/logout HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}
