version: '3.8'

services:
  postgres:
    container_name: nest-with-prisma-pg
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-with-prisma
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

volumes:
  postgres_data:
